# -*- coding: utf-8 -*-
"""univariate on company.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XP8DGV7aMZX-pweAZ_1iiK0dgJoguZhV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('/content/Company.csv')
data.head()

data.tail()

data.isnull().sum()

data.info()

data.describe()

data.corr()

X=data['TV'].values
y=data['Sales'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)



"""training model"""

from sklearn.linear_model import LinearRegression
modx=X_train.reshape(-1,1)
mody=y_train.reshape(-1,1)
model=LinearRegression()
model.fit(modx,mody)



xt=X_test.reshape(-1,1)
yt=y_test.reshape(-1,1)
y_pred=model.predict(xt)
from sklearn import metrics
print("MAE",metrics.mean_absolute_error(y_test,y_pred))
print("MSE",metrics.mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
print("R2 score",metrics.r2_score(y_test,y_pred))

